config/routes.rb
Rails.application.routes.draw do
  
  root 'cars#index'
  
  resources :cars
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    validates :make, presence: true
    validates :name, presence: true
    validates :price, presence: true
    
    mount_uploader :picture, PictureUploader
    
    
    def picture_size
       if picture_size > 5.megabytes
           errors.add(:picture, "should be less than 5MB")
       end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    
    def index
       @cars = Car.all 
    end
    
    def new
        @car = Car.new
    end
    
    def create
    @car = Car.new(car_params)
    if @car.save
        flash[:success] = "Car sucessfully created"
        redirect_to car_path(@car)
    else
        render 'new'
    end
    end
    
    def show
       @car = Car.find(params[:id]) 
    end
    
    def edit
       @car = Car.find(params[:id]) 
    end
    
    def update
       @car = Car.find(params[:id])
       if @car.update(car_params)
           flash[:success] = "Car Details sucessfully updated"
           redirect_to car_path(@car)
       else
           render 'edit'
       end
    end
    
    def destroy
       @car = Car.find(params[:id])
       @car.destroy
       flash[:danger] = "Car details  deleted"
       redirect_to cars_path
    end
    
    private
    
    def car_params
       params.require(:car).permit(:make, :name, :price, :description, :picture) 
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cars/_errors.html.erb
<% if @car.errors.any? %>
 <div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading" id="top-alert">
    <h2 class="panel-title">
      <%= pluralize(@car.errors.count, "error") %> prohibited this <%= @car.class %> from being saved: <!-- Solution from recipes_test_rb 46 -->
      <a href="#" class="close" data-dismiss="panel">&#215;</a>
     </h2>
      <div class="panel-body">
       <ul>
        <% @car.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/cars/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-green ">
                <%= form_for(@car, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          
               <div class="form-group">
                 <div class="control-label col-md-2">
                    <%= f.label :make %> 
                 </div>
                 <div class="col-md-8">
                   <%= f.text_field :make, class: 'form-control', placeholder: "Make of car", autofocus: true %>
                 </div>
               </div>
               
                <div class="form-group">
                 <div class="control-label col-md-2">
                    <%= f.label :model %> 
                 </div>
                 <div class="col-md-8">
                   <%= f.text_field :name, class: 'form-control', placeholder: "Model", autofocus: true %>
                 </div>
               </div>
               
                <div class="form-group">
                 <div class="control-label col-md-2">
                    <%= f.label :price %> 
                 </div>
                 <div class="col-md-8">
                   <%= f.text_field :price, class: 'form-control', placeholder: "Price of car", autofocus: true %>
                 </div>
               </div>
              
              <div class="form-group">
                 <div class="control-label col-md-2">
                    <%= f.label :description %> 
                 </div>
                 <div class="col-md-8">
                   <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: "Add description of car" %>
                 </div>
               </div>
               
               <div class="form-group">
                 <div class="control-label col-md-2">
                    <%= f.label :picture %> 
                 </div>
                 <div class="col-md-8">
                   <%= f.file_field :picture, class: 'form-control', placeholder: "Add car image here" %>
                 </div>
               </div>
              
              
              
              <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                  <%= f.submit class: "btn btn-primary" %> 
                  <%= link_to "Back to AllCars", cars_path, class: "btn btn-warning" %>
                </div>
              </div>
            <% end %>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
   $(‘#car_picture').bind('change', function() {
     var size_in_megabytes = this.files[0].size/1024/1024;
     if (size_in_megabytes > 5) {
       alert('Maximum file size is 5MB. Please choose a smaller file.');
     }
   });
 </script>

app/views/cars/edit.html.erb
<%= render 'layouts/flash' %>
<div align="center">
    <h2 class="page-title">Edit Car Details</h2>
</div>

<div class="container">
    <div align="center">
        <%= render 'errors' %>

        <%= render 'cars/form' %>
    </div>
</div>

app/views/cars/index.html.erb
<%= render 'layouts/flash' %>
<div class="container">
    <div align="center">
        <h1 class="page-title">The Car Bar</h1>
    </div>
    <br />
</div>
<div class="container">
   <div class="row">
        <div align="center">                 
        <table class="table">
           <thead>
                <tr>
                <!-- <th scope="col"><span class="hide">Money</span></th> -->
                <th scope="col">Make</th>
                <th scope="col">Image</th>
                <th scope="col">Model</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
            </tr>
           </thead>
            <% @cars.each do |car| %>
                <tr class="well well-green <%= cycle('', 'well-white') %>"
                    <th scope="row car-block">
                            <td class="show-text"><%= car.make %></td>
                            <td ><%= image_tag(car.picture_url, :size => "50px", class: "pic") if car.picture? %></td>
                            <td><%=link_to car.name, car_path(car), class: "make" %></td>
                            <td>£ <%= car.price %></td>
                            <td><%= car.description %></td>
                            <td><%= link_to "View", car_path(car), class: "btn btn-primary index-button" %></td>
                    </th>
                </tr>
            <% end %>
            
          
        </table>
    </div>
     
   </div>
    
</div>

app/views/cars/new.html.erb
<%= render 'errors' %> 
<div class="container">
        <div class="row">
            <div class="col-md-3 col-md-offset-4">
                <div align="center">
                    <h2 class="page-title">Add a New Car</h2>
                </div>
            </div>
        </div>
        

        <%= render 'cars/form' %>
    </div>
</div>

app/views/cars/show.html.erb
<div class="container">
    <div align="center">
        <h2 class="page-title"> <%= @car.make %> <%= @car.name %></h2>
    </div>
</div>

<div class="container show-block">
        <div align="center">
        <div class="">
        <p>
            Make: <%= @car.make %> 
        </p>
        <p>
            Model: <%= @car.name %>
        </p>
        <p>
            Description: <%= @car.description %>
        </p>
        <p>
            Price: £<%= @car.price %>
        </p>
        </div>
        <p>
             <%= image_tag @car.picture.url, class: "mainPic" if @car.picture? %>
        </p>
    
        <p>
            <%= link_to "Edit", edit_car_path(@car), class: "btn btn-primary" %>
            <%= link_to "Cars", cars_path, class: "btn btn-warning" %>
            <%= link_to "Delete", car_path(@car), method: :delete,  class: "btn btn-danger" %>
        </p>
    </div>
    
</div>

app/views/layouts/_flash.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= msg %>
        </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
            <div class="row">
              <div class="col-md-12">
                <!-- Footer -->
<!-- <div class="footer navbar-fixed-bottom"> -->
<!-- <footer class="footer navbar-fixed-bottom font-small cyan darken-3"> -->

    <!-- Footer Elements -->
    <div class="container">

      <!-- Grid row-->
      <div class="row">

        <!-- Grid column -->
      
          <div class="col-md-12 py-5">
          <div class="mb-5 flex-center">

           
            <div class="footer-copyright text-center py-3">
                <%= render "layouts/footerSocialMedia" %>
                <br />
                <span>Created By Vincent Walker</span>
                <%= link_to "Car Bar", root_path, class: "pull-right copyright" %>
           </div>
          </div>
        </div>
        
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright 
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://vincethewalker.com/"> Vincent Walker</a>
       <a class="" href="#!"><%#= link_to "Car Bar", root_path, class: "pull-right" %></a>
    </div>
    Copyright -->

  <!--</footer> -->
  
 

app/views/layouts/_footerSocialMedia.html.erb
            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fa fa-facebook-square fa-sm fa-2x"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fa fa-twitter fa-lg fa-2x"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fa fa-instagram fa-lg fa-2x"> </i>
            </a>
            <!--Pinterest-->
            <a class="pin-ic">
              <i class="fa fa-pinterest fa-lg white-text fa-2x"> </i>
            </a>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cars", cars_path %></li>
          <li><%= link_to "Add a New Car", new_car_path %></li>
        </ul>
        
        <ul>
          <li class="left-nav-bar">
            <%= link_to root_path class: "nav navbar-nav navbar-left" do %>
                <i class="fa fa-car"></i><span class="white"> CarBar</span>
              <% end %> 
          </li>  
         </ul>
      </div>
    </nav>
  </div>
</header>




  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CarBar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/> 
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome/css/font-awesome.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <%= render 'layouts/navbar' %>
      </header>
      
        <main>
          <div class="container">
            <%= render "layouts/flash" %>
             
           <div class="page-alignment">
              <%= yield %>
           </div>
          </div>
        </main>
        
        <footer class="footer navbar-fixed-bottom navbar-inverse font-small"  id="page-footer">
          <%= render 'layouts/footer' %>
        </footer>
        
  </body>
</html>

app/views/pages/home.html.erb
<div align="center">
    <div class="jumbotron head-banner">
        <h1 class="white">Car Bar</h1>
    </div>
</div>